[package]
name = "vport_management"
version = "1.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }

[addresses]
VPORT_MANAGEMENT = "0x5f6f6140fc53d3e6951a85ae4358f7f3646232a7a0fa347fbceb39b93194e5ba"  